#!/bin/sh
cat <<EOF
Content-type: video/mp4

EOF
VIDEOURL="http://r1.fr-rbx.web.qazwsx.work:25461/live/I02CzDS14C/EHdAiyOOS0/55.m3u8?token=QxBQABZZRAgbVAEBAQgFUQcIVw8NUFpZCAFVUQBWCAEPAVkHUQRXUF8SGBJDTURSAFQ7UVwTAwkcF0NBB0BvWFwQAkNWCF8LCBIYEkRQW1JDA1QUGkFQXBIPFANbCwAFGh4aBB1FA0BXUVhvVFxAXgJcRgJWRFVUHBdZXD1WVVxZXFxDXxNWEBUSXUNAGwwVJVAWXVtFGXdeUBZhIxAcE1pbTBMERQMQAxIGBwgBFBtDWgtNVkVLQRIPFGAtEBwTXUpMBAtCD11XEg4SXQpDD0MVRlFLbktdQ0FEVwNfVUMaCBpRRx1EX1hIa1NfV1hSAk0NV1ZCGwISBBQeQF9fX1FGVxM6QQ9WGwoWAQANDwZDRA=="
exec /usr/local/bin/Resource/www/cgi-bin/scripts/wget -q -c -U 'Mozilla/5.0' "$VIDEOURL" -O- | /usr/local/bin/Resource/www/cgi-bin/scripts/wget -q -i - -U 'Mozilla/5.0' -O -
